[features]
seeds = false
skip-lint = false

[programs.localnet]
battleship = "DRJk4gJFdYCCHNYY5qFZfrM9ysNrMz3kXJN5JVZdz8Jm"

[programs.devnet]
battleship = "DRJk4gJFdYCCHNYY5qFZfrM9ysNrMz3kXJN5JVZdz8Jm"

[programs.mainnet]
battleship = "DRJk4gJFdYCCHNYY5qFZfrM9ysNrMz3kXJN5JVZdz8Jm"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://gorchain.wstf.io"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[workspace]
types = "target/types" 